services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "~springboot1794Zz!"

  java-backend:
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "~springboot1794Zz!"
