#!/bin/bash
set -euo pipefail

MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql -uroot <<SQL
CREATE DATABASE IF NOT EXISTS BUCTTA_DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'java_springboot_buctta'@'%' IDENTIFIED BY '${JAVA_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, EXECUTE, SHOW VIEW
    ON BUCTTA_DATABASE.*
    TO 'java_springboot_buctta'@'%';

CREATE USER IF NOT EXISTS 'python_flask_buctta'@'%' IDENTIFIED BY '${PYTHON_DB_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
    ON BUCTTA_DATABASE.*
    TO 'python_flask_buctta'@'%';

FLUSH PRIVILEGES;
SQL
